name: Build release apk

on:
  [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Load API Token from secrets
      env:
        API_TOKEN: ${{ secrets.API_OTKEN }}
      run: echo API_TOKEN=\"$API_TOKEN\" > ./local.properties

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Prepare for build
      run: ./gradlew GenerateMetadataByCountry
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - uses: actions/upload-artifact@v2
      with:
        name: release.apk
        path: ${{steps.sign.outputs.signedReleaseFile}}

    - name: Rename APK
      run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/StreetComplete-release-$(git log -n 1 --format='%h').apk
    - name: Archive APK
      uses: actions/upload-artifact@v2
      with: 
        name: release-apk
        path: app/build/outputs/apk/release/*.apk
        retention-days: 1
