name: Android build APK
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Android problem matchers
      uses: jonasb/android-problem-matchers-action@v1
    - name: Build the app
      run: |
        ./gradlew assembleDebug && mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/StreetComplete-mnalis-helium314-questorder-debug.apk
    - name: Upload apk
      uses: actions/upload-artifact@v2
      with:
        name: debug apk
        path: app/build/outputs/apk/debug/StreetComplete-mnalis-helium314-questorder-debug.apk
